### ISSUE TITLE
Error: getaddrinfo ENOTFOUND ore.spoongepowered.org

### ISSUE THREAD

**Issue by AuroraLS3** [dualspiral/ore-upload-action#41]
Hello,

I'm having some issues setting this up. I'm trying to set it up so that the github action uploads to Ore when a new github release is created. Yesterday the action failed with the error that's in the title.

Do you have any advice? 

Thanks in advance.

<details>
<summary>Action config</summary>

```yml
name: Release

on:
  release:
    types: [ published ]

jobs:
  upload_release_ore:
    name: Ore Upload
    runs-on: ubuntu-latest
    steps:
      - name: Download release artifact for upload
        run: |
          curl 'https://api.github.com/repos/plan-player-analytics/plan/releases/${{ github.event.release.id }}/assets' | jq -r '.[] | {name: .name, url: .browser_download_url} | select(.url | strings | test("Fabric") | not)' > asset.txt
          jq -r '.url' asset.txt > url.txt
          jq -r '.name' asset.txt > name.txt
          wget -i url.txt
          echo "JAR_FILENAME=$(cat name.txt)" >> $GITHUB_ENV
      - name: Upload artifact for ore upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.release.name }}
          path: ${{ env.JAR_FILENAME }}
      - name: Upload release to Ore 🚀
        if: ${{ github.event.release.prerelease == false }}
        uses: dualspiral/ore-upload-action@v1
        with:
          plugin: ${{ github.event.release.name }}
          description: ${{ github.event.release.body }}
          apiKey: ${{ secrets.ORE_API_TOKEN }}
          channel: Release
          pluginId: plan
          createForumPost: true
      - name: Upload DEV release to Ore 🚀
        if: ${{ github.event.release.prerelease == true }}
        uses: dualspiral/ore-upload-action@v1
        with:
          plugin: ${{ github.event.release.name }}
          description: ${{ github.event.release.body }}
          apiKey: ${{ secrets.ORE_API_TOKEN }}
          channel: DEV
          pluginId: plan
          createForumPost: false
```

</details>
<details>
<summary>Action log</summary>

```
Run dualspiral/ore-upload-action@v1
  with:
    plugin: 5.5 DEV build 1833
    description: # 5.5 DEV build 1833
  
  This update contains update to Java 11, Sponge API 8, Fabric 1.19.1, as well as Webserver rewrite to use Jetty. In addition new features such as Access logging & Swagger are available.
  
  This version **updates config** so backup your config in case you need to revert back to 5.4!
  
  Special thanks to **Vankka**, **Kopo** and **Drex** for contributions to this update
  
  Untested features:
  - Fabric join address gathering, unknown if new addresses are correct format.
  
  ## Bugfixes from DEV build 1791
  
  - Fabric
    - Fabric 1.19.1 is now supported. Fabric 1.19 is no longer supported. Thanks Drex!
    - Fabric now starts Plan webserver properly if HTTPS is enabled
    - Fabric now gets HTTP/2 enabled since ALPN protocol provider is loaded properly
    - Fabric should now gather join addresses correctly. Previously player IPs were gathered by mistake. To clear the invalid data use `/plan db removejoinaddresses {servername}` once you install the plugin.
  - Velocity
    - Velocity now starts properly with slf4j logger and all
  - Bugfixes
    - Jetty no longer holds the server hostage and shuts down properly on server shutdown
    - Reduced maximum join address length to 191 characters due to limitation of old MySQL versions
    - Added primary keys to all database tables (Fix not applied retroactively, since this is to allow installing on servers where MySQL mandates primary keys for all tables)
  - Other
    - Increased default inactive player removal theshold 180 days -> 3650 days (10 years). This change is not applied automatically, only new configs.
    - Added log message about HTTPS certificate expiry date, and warning if it is less than 7 days from now
    - Reworked player join and leave event handling to reduce duplicate code
  
  # Change Log
  
  ## Java 11
  
  - Plan now requires Java 11 or newer to run. This version is required for Sponge API 8, Jetty and other dependency updates.
  - Java 8 is no longer supported. If you are unable to update, you can continue using [5.4 build 1722](https://github.com/plan-player-analytics/Plan/releases/tag/5.4.1722) even if connected to same database.
  - Plan API jar is still compiled with Java 8 to provide backwards compatibility for other plugins, so the use of Plan API doesn't force you to update your plugin to need Java 11.
  
  ## Sponge API 8
  
  - Vankka implemented Sponge API 8 changes. Sponge API 7 is no longer supported. If you are unable to update, you can continue using [5.4 build 1722](https://github.com/plan-player-analytics/Plan/releases/tag/5.4.1722) even if connected to same database.
  
  ## Fabric
  
  - Drex implemented support for Fabric 1.19.1
  - Fabric should now gather join addresses correctly. Previously player IPs were gathered by mistake. To clear the invalid data use `/plan db removejoinaddresses {servername}` once you install the plugin.
  
  ## Jetty Webserver
  
  - Replaced Sun Webserver with Jetty (https://www.eclipse.org/jetty/), an open source embedded webserver library. 
  - Plan now supports HTTP/2
  - Plan now supports TLSv1.3 for HTTPS, and browsers have a larger selection of cipher suites they can use.
    - Users of PlanCert.jks (Included in the jar) are encouraged to create their own self signed cert. I had to implement some extra code to support expired certificate (Since PlanCert.jks inside the jar has expired), and that may not be as secure as creating a new self-signed .p12 - Instructions will be added to the wiki, but the plugin also logs the instructions if you use that cert.
  
  ### Access log
    
  Access logs are now stored in Plan database in plan_access_log table.
  
  - You can also log access to console with `Webserver.Security.Access_log.Print_to_console` (default false) in the config. This is useful for debugging reverse-proxy issues. 
  - The IP of each request is stored in the database - as it is necessary for security (a valid legal basis for use with GDPR). 
  - The request logs in database are removed after `Webserver.Security.Access_log.Remove_logs_after_days` (default 30)
  
  ### Swagger
  
  Plan json endpoints are now documented with Swagger available on the webserver itself. You can access the Swagger documentation from `/docs` on your Plan webserver after updating.
  
  ## Removal of some deprecated internal code
  
  - Removed ServerKeys, some PlayerKeys fields as well as PlayerDeath class. This code has been deprecated since 5.0.
  
  ## Commands and permissions
  
  - Added `plan.command` permission (default: true) on Spigot servers to allow hiding /plan command from tab completion by negating this permission
  
  ## Config
  
  - Config structure was modified to be valid yaml so that other programs can validate it. The structure is updated automatically with same values for old versions of the config.
  - Increased default inactive player removal theshold 180 days -> 3650 days (10 years). This change is not applied automatically, only new configs.
  
  ## Extensions
  
  - Plugin method calls should no longer be made during Plan disable.
  - Redprotect and Nucleus disabled temporarily as the extension code still needs to be updated to Sponge API 8
  
  ## Build & Automation
  
  - Restructured Github Actions builds to have less workflow files
  - Automated Ore uploads
  - Dev builds for every commit is now available [DEV build pipeline](https://github.com/plan-player-analytics/Plan/actions/workflows/ci.yml?query=branch%3Amaster) (Click on title and scroll down to Artifacts)
  - Automated version.txt update on release (The file which Plan reads for update information)
  - Restructured gradle configurations to better utilize shadowJar and reduce amount of code IntelliJ IDEA needs to index after each build.
  
  ## Other
  
  - Fixed lag caused by large tab completion results if server had a lot of players and someone tab completed `/plan player `.
  - Fixed empty cookies preventing Plan login due to error
  - Updated geoip2, caffeine & HikariCP to versions that needed Java 11
  - Reduced maximum join address length to 191 characters due to limitation of old MySQL versions
  - Added primary keys to all database tables (Fix not applied retroactively, since this is to allow installing on servers where MySQL mandates primary keys for all tables)
  - Added log message about HTTPS certificate expiry date, and warning if it is less than 7 days from now
  - Reworked player join and leave event handling to reduce duplicate code
    apiKey: ***
    channel: DEV
    pluginId: plan
    createForumPost: false
    oreUrl: https://ore.spoongepowered.org/
    verboseLogging: false
  env:
    JAR_FILENAME: Plan-5.5-dev-build-1833.jar
Directory structure has been setup for the artifact
Total number of files that will be downloaded: 1
<ref *2> Writable {
  _writableState: WritableState {
    objectMode: false,
    highWaterMark: 16384,
    finalCalled: false,
    needDrain: false,
    ending: false,
    ended: false,
    finished: false,
    destroyed: false,
    decodeStrings: true,
    defaultEncoding: 'utf8',
    length: 0,
    writing: false,
    corked: 0,
    sync: true,
    bufferProcessing: false,
    onwrite: [Function: bound onwrite],
    writecb: null,
    writelen: 0,
    afterWriteTickInfo: null,
    buffered: [],
    bufferedIndex: 0,
    allBuffers: true,
    allNoop: true,
    pendingcb: 0,
    constructed: true,
    prefinished: false,
    errorEmitted: false,
    emitClose: true,
    autoDestroy: true,
    errored: null,
    closed: false,
    closeEmitted: false,
    [Symbol(kOnFinished)]: []
  },
  _events: [Object: null prototype] {
    response: [Function: handleResponse],
    error: [Function: handleRequestError],
    socket: [Function: handleRequestSocket]
  },
  _eventsCount: 3,
  _maxListeners: undefined,
  _options: {
    maxRedirects: 21,
    maxBodyLength: 10485760,
    protocol: 'https:',
    path: '/api/v2/authenticate',
    method: 'POST',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      Authorization: 'OreApi apikey="***"',
      'User-Agent': 'axios/0.27.2',
      'Content-Length': 18
    },
    agent: undefined,
    agents: { http: undefined, https: undefined },
    auth: undefined,
    hostname: 'ore.spoongepowered.org',
    port: null,
    nativeProtocols: { 'http:': [Object], 'https:': [Object] },
    pathname: '/api/v2/authenticate'
  },
  _ended: false,
  _ending: true,
  _redirectCount: 0,
  _redirects: [],
  _requestBodyLength: 18,
  _requestBodyBuffers: [
    {
      data: <Buffer 7b 22 65 78 70 69 72 65 73 5f 69 6e 22 3a 31 32 30 7d>,
      encoding: undefined
    }
  ],
  _onNativeResponse: [Function (anonymous)],
  _currentRequest: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      response: [Function],
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: null,
    _hasBody: true,
    _trailer: '',
    finished: false,
    _headerSent: true,
    _closed: false,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: false,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: true,
      _SNICallback: null,
      servername: null,
      alpnProtocol: null,
      authorized: false,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 11,
      connecting: false,
      _hadError: true,
      _parent: null,
      _host: 'ore.spoongepowered.org',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: [Array],
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: null,
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: false,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 11024,
      [Symbol(kHandle)]: null,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    _header: 'POST /api/v2/authenticate HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: application/json\r\n' +
      'Authorization: OreApi apikey="***"\r\n' +
      'User-Agent: axios/0.27.2\r\n' +
      'Content-Length: 18\r\n' +
      'Host: ore.spoongepowered.org\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/api/v2/authenticate',
    _ended: false,
    res: null,
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'ore.spoongepowered.org',
    protocol: 'https:',
    _redirectable: [Circular *2],
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      authorization: [Array],
      'user-agent': [Array],
      'content-length': [Array],
      host: [Array]
    }
  },
  _currentUrl: 'https://ore.spoongepowered.org/api/v2/authenticate',
  [Symbol(kCapture)]: false
}
Error: Error: getaddrinfo ENOTFOUND ore.spoongepowered.org
```

</details>
